package net.forevents.foreventsandroid.Util

object Constants {
    val PMANAGER_ID_USER = "PMANAGER_ID_USER"
    val PMANAGER_TOKEN_USER = "PMANAGER_TOKEN_USER"
    val PMANAGER_FAVORITE_PARAMETERS_SEARCH = "PMANAGER_FAVORITE_PARAMETERS_SEARCH"


}